# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.
#WARNING_FLAGS="-Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing"

COMMON_FLAGS="-march=native -O2 -pipe" # ${WARNING_FLAGS}"
CFLAGS="${COMMON_FLAGS} -flto=thin"
CXXFLAGS="${COMMON_FLAGS} -flto=thin"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
LD_FLAGS="-Wl, -O2 -Wl,--as-needed"
RUST_FLAGS="${RUSTFLAGS} -C target-cpu=native opt-level=3"

CC="clang"
CPP="clang-cpp"
CXX="clang++"
AR="llvm-ar"
NM="llvm-nm"
RANLIB="llvm-ranlib"

# NOTE: This stage was built with the bindist USE flag enabled
MAKEOPTS="-j12 -l13"
ACCEPT_LICENSE="*"
VIDEO_CARDS="nvidia"
PORTAGE_SCHEDULING_POLICY="idle"
EMERGE_DEFAULT_OPTS="--jobs=12 --load-average=12 --keep-going --verbose --quiet-build --with-bdeps=y --complete-graph=y --deep --ask --autounmask=y"
USE="-doc -gtk-doc -fortran -gtk -gnome -cdr -dvd -systemd -webengine alsa bluetooth dist-kernel wayland dbus pipewire threads clang vulkan screencast jit"
FEATURES="candy fixlafiles unmerge-orphans noman nodoc noinfo notitles parallel-install parallel-fetch clean-logs ccache"
CCACHE_DIR="/var/cache/ccache"
POSTDIR="/var/db/repos/gentoo"
DISTDIR="/var/cache/distfiles"
PKGDIR="/var/cache/binpkgs"


# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C.UTF-8

GENTOO_MIRRORS="https://mirror.it4i.cz/gentoo \
    http://ftp.fi.muni.cz/pub/linux/gentoo/ \
    https://mirror.dkm.cz/gentoo/ \
    https://gentoo.mirrors.ovh.net/gentoo-distfiles/ \
    https://ftp.agdsn.de/gentoo \
    https://ftp.spline.inf.fu-berlin.de/mirrors/gentoo/ \
    https://ftp.gwdg.de/pub/linux/gentoo/ \
    https://ftp.uni-hannover.de/gentoo/ \
    https://linux.rz.ruhr-uni-bochum.de/download/gentoo-mirror/ \
    https://ftp.halifax.rwth-aachen.de/gentoo/ \
    https://ftp-stud.hs-esslingen.de/pub/Mirrors/gentoo/ \
    https://ftp.uni-stuttgart.de/gentoo-distfiles/ \
    http://ftp.ntua.gr/pub/linux/gentoo/"
GRUB_PLATFORMS="efi-64"
