#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &
~/.config/polybar/launch.sh &
nitrogen --restore &
picom &
dunst &
polkit &
/usr/libexec/geoclue-2.0/demos/agent &
redshift -c ~/.config/redshift.conf &
keepassxc &
syncthing &
qbittorrent &
xscreensaver

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         0
bspc config window_gap          10
bspc config top_padding         39
bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
