#! /bin/sh

# Launch firefox on workspace 1
bspc rule -a Firefox desktop=^1 follow=off -o
if ! pgrep -x "firefox" > /dev/null; then
  firefox &
fi

# Launch ferdium on workspace 2
bspc rule -a Ferdium desktop=^2 follow=off -o
if ! pgrep -x "org.ferdium.Ferdium" > /dev/null; then
  flatpak run org.ferdium.Ferdium &
fi

# Launch terminal on workspace 3
bspc rule -a Alacritty desktop=^3 follow=off -o
if ! pgrep -x "alacritty" > /dev/null; then
  alacritty --config-file ~/alacritty.yaml -e fish &
fi

# Launch steam on workspace 5
bspc rule -a Steam desktop=^5 follow=off -o
if ! pgrep -x "steam" > /dev/null; then
  steam &
fi

# Launch Lutris on workspace 5
bspc rule -a Lutris desktop=^5 follow=off -o
if ! pgrep -x "lutris" > /dev/null; then
  lutris &
fi

pgrep -x sxhkd > /dev/null || sxhkd &
~/.config/polybar/launch.sh &
nitrogen --restore &
picom &
dunst &
lxqt-policykit-agent &
/usr/libexec/geoclue-2.0/demos/agent &
#if ! pgrep -x "redshift" > /dev/null; then
  redshift -c ~/.config/redshift.conf &
#fi
if ! pgrep -x "keepassxc" > /dev/null; then
  keepassxc &
fi
syncthing &
xscreensaver &
if ! pgrep -x "flameshot" > /dev/null; then
  flameshot &
fi
ibus-daemon --xim &
xsetroot -cursor_name left_ptr

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width          0
bspc config window_gap            8
bspc config top_padding           40
bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
