user "nxtperfect"
music_directory      "/home/nxtperfect/Music"
# Recommended location for database
db_file                 "/home/nxtperfect/.mpd/database"

playlist_directory   "/home/nxtperfect/Music/playlists"
# log_file             "/var/lib/mpd/log"
# state_file           "/var/lib/mpd/state"

# Input
input {
        plugin          "curl"
}

# PulseAudio output
audio_output {
        type            "pipewire"
        name            "Pipewire Output"
}
